// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egqijvoaicgqsiwastbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncWlqdm9haWNncXNpd2FzdGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MzE2NTIsImV4cCI6MjA2MzAwNzY1Mn0.7V0r5hwfNl5jKDbAjePaTTl5cMIsS3ehlNBBokRxbNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);